<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>Library</OutputType>
    <AssemblyName>Terminals.Common</AssemblyName>
    <RootNamespace>Terminals.Common</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Deterministic>false</Deterministic>
    <EnableDefaultEmbeddedResourceItems>false</EnableDefaultEmbeddedResourceItems>
  </PropertyGroup>


  <ItemGroup>
    <PackageReference Include="log4net" Version="2.0.17" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System" />
    <Reference Include="System.configuration" />
    <Reference Include="System.Core" />
    <Reference Include="System.Data" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="System.Drawing" />
    <Reference Include="System.Net.Http" />
    <Reference Include="System.Windows.Forms" />
    <Reference Include="System.Xml" />
    <Reference Include="System.Xml.Linq" />
    <Reference Include="Microsoft.CSharp" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="DesktopSizeCalculator.cs" />
    <Compile Include="..\Terminals\Properties\Common.AssemblyInfo.cs">
      <Link>Properties\Common.AssemblyInfo.cs</Link>
    </Compile>
    <EmbeddedResource Include="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Include="Connections\Connection.resx">
      <DependentUpon>Connection.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Forms\CredentialsPanel.resx">
      <DependentUpon>CredentialsPanel.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Forms\InputBox.resx">
      <DependentUpon>InputBox.cs</DependentUpon>
    </EmbeddedResource>
  </ItemGroup>

</Project>
