<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>Library</OutputType>
    <AssemblyName>Metro</AssemblyName>
    <RootNamespace>Metro</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="System.Xml" />
    <Reference Include="ZedGraph">
      <HintPath>..\..\Resources\Libraries\ZedGraph\ZedGraph.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
  </ItemGroup>

</Project>
