<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>Library</OutputType>
    <AssemblyName>Tests</AssemblyName>
    <RootNamespace>Tests</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EntityFramework" Version="5.0.0" />
    <PackageReference Include="SharpZipLib" Version="1.3.3" />
    <PackageReference Include="log4net" Version="2.0.17" />
    <PackageReference Include="Moq" Version="4.2.1408.0717" />
    <PackageReference Include="Microsoft.VisualStudio.QualityTools.UnitTestFramework.Updated" Version="15.0.26228" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="AxInterop.MSTSCLib">
      <HintPath>..\..\Resources\Libraries\mstsc\AxInterop.MSTSCLib.dll</HintPath>
    </Reference>
    <Reference Include="MSTSCLib">
      <HintPath>..\..\Resources\Libraries\mstsc\MSTSCLib.dll</HintPath>
    </Reference>
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="System.Data" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="System.Drawing" />
    <Reference Include="System.Management" />
    <Reference Include="System.Windows.Forms" />
    <Reference Include="System.Xml" />
    <Reference Include="System.Xml.Linq" />
    <Reference Include="Microsoft.CSharp" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HexEditor\HexEditor.csproj" />
    <ProjectReference Include="..\Metro\Metro.csproj" />
    <ProjectReference Include="..\TabControl\TabControl.csproj" />
    <ProjectReference Include="..\Terminals\Terminals.csproj" />
    <ProjectReference Include="..\Terminals.Common\Terminals.Common.csproj" />
    <ProjectReference Include="..\Terminals.External\Terminals.External.csproj" />
    <ProjectReference Include="..\Terminals.Plugins.Putty\Terminals.Plugins.Putty.csproj" />
    <ProjectReference Include="..\Terminals.Plugins.Rdp\Terminals.Plugins.Rdp.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="App.config" />
    <None Include="Terminals.exe.config">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <!-- Test data files used through DeploymentItem attributes -->
  <ItemGroup>
    <Content Include="..\..\Resources\Libraries\mstsc\AxInterop.MSTSCLib.dll">
      <Link>AxInterop.MSTSCLib.dll</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\..\Resources\Libraries\mstsc\MSTSCLib.dll">
      <Link>MSTSCLib.dll</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\Terminals\Resources\ControlPanel.png">
      <Link>ControlPanel.png</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\..\Resources\Database\Terminals.mdf">
      <Link>Terminals.mdf</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\..\Resources\Database\Terminals_log.LDF">
      <Link>Terminals_log.LDF</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\..\Resources\TestData\EmptyCredentials.xml">
      <Link>EmptyCredentials.xml</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\..\Resources\TestData\Issue_21279_import_800_items.xml">
      <Link>Issue_21279_import_800_items.xml</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\..\Resources\TestData\NoMasterCredentials.xml">
      <Link>NoMasterCredentials.xml</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\..\Resources\TestData\SecuredCredentials.xml">
      <Link>SecuredCredentials.xml</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\..\Resources\TestData\SshTelnet_Favorites_401.xml">
      <Link>SshTelnet_Favorites_401.xml</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\..\Resources\TestData\EmptyTerminals.config">
      <Link>EmptyTerminals.config</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\..\Resources\TestData\NoMasterTerminals.config">
      <Link>NoMasterTerminals.config</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\..\Resources\TestData\SecuredTerminals.config">
      <Link>SecuredTerminals.config</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\..\Resources\TestData\Terminals.config">
      <Link>Terminals.config</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\..\Resources\TestData\RdcManGroupsAndFavorites.rdg">
      <Link>RdcManGroupsAndFavorites.rdg</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\..\Resources\TestData\RdcManGroupsEmpty.rdg">
      <Link>RdcManGroupsEmpty.rdg</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\..\Resources\TestData\RdcManInheritedProperties.rdg">
      <Link>RdcManInheritedProperties.rdg</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\..\Resources\TestData\RdcManRootServers.rdg">
      <Link>RdcManRootServers.rdg</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
