<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <MsRdpExComInterop>Legacy</MsRdpExComInterop>
    <MsRdpExGeneratedWinForms>false</MsRdpExGeneratedWinForms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Devolutions.MsRdpEx" Version="2026.10.6" />
  </ItemGroup>

</Project>
